#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FridgeDate.Android.Resource", IsApplication=true)]

namespace FridgeDate.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Splat.Resource.String.library_name = global::FridgeDate.Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050003
			public const int dark = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int facebook_dark = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int facebook_primary = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int light = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int primary = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int primary_dark = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int secondary = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int twitter_dark = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int twitter_primary = 2131034119;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060001
			public const int buttonMargin = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int buttonPadding = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int layoutPadding = 2131099650;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int facebook_btn = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fridge_btn = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int twitter_btn = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int btnDelete = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int btnFacebook = 2131230724;
			
			// aapt resource value: 0x7f08000b
			public const int btnLoginLocal = 2131230731;
			
			// aapt resource value: 0x7f080010
			public const int btnRegisterLocal = 2131230736;
			
			// aapt resource value: 0x7f080005
			public const int btnTwitter = 2131230725;
			
			// aapt resource value: 0x7f08000c
			public const int content = 2131230732;
			
			// aapt resource value: 0x7f080003
			public const int flLogin = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int lblDaysLeft = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int lblName = 2131230720;
			
			// aapt resource value: 0x7f080009
			public const int linearLayout2 = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int linearLayout4 = 2131230730;
			
			// aapt resource value: 0x7f08000d
			public const int lwItems = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int tbEmail = 2131230734;
			
			// aapt resource value: 0x7f080007
			public const int tbLoginEmail = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int tbLoginPassword = 2131230728;
			
			// aapt resource value: 0x7f08000f
			public const int tbPassword = 2131230735;
			
			// aapt resource value: 0x7f080006
			public const int txtRegister = 2131230726;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FoodItemForUser_ListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListFragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LoginFragment = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int LoginLocalFragment = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int RegisterLocal = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int EnterEmail = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int EnterPassword = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int FridgeTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int button_text = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
